[package]
name = "zincite-lint"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "MiniZinc source lint advice"

[dependencies]
zincite-syntax = { path = "../zincite-syntax" }
toml = { version = "1.1.2", default-features = false, features = ["parse", "serde", "std", "display"] }
